### ISSUE TITLE
brilliant

### ISSUE THREAD

**Issue by jonschlinkert** [vfmd/vfmd-spec#5]
This is great! I really like what you're doing here. But I have a few questions... why? What is your motivation for this? Have you started building the parser? 

I'm asking because I'm curious, but I'm also potentially interested in helping with this. I think what you've done here is thorough, well though-out, pragmatic and insightful. I don't think this should be a "variant" of markdown. I think this should be promoted as an THE official spec that markdown has been missing.

**Comment by roop** [comment]
Thanks. Your comment made my day :). (But sorry about not noticing your comment earlier.)

Motivation: I'm working on an iOS app where Markdown is a key part, and the value proposition of the app would be much higher with a standardized Markdown. So, I set out to try and make a standardized Markdown myself. I'd really like vfmd to become the canonical way of parsing Markdown. I only call it a variant because, to be fair, it's slightly different from Gruber's Markdown (as described in [differences](http://vfmd.github.io/differences/)).

I am working on a parser, and I just pushed my progress to the [vfmd-src repo](https://github.com/vfmd/vfmd-src). Later, I also plan to add SWIG bindings so that the parser can be used (and extended for additional syntaxes) from Python and Ruby.

**Comment by jonschlinkert** [comment]
Awesome! Thanks for sharing your thoughts. I see your point regarding John Gruber's Markdown, but I think it's acceptable for a "real" specification to delineate slightly from an initial proposal (some official specs are very different than initial intent). 

I'll continue to watch progress! Thanks!

**Comment by roop** [comment]
The parser is almost done. I'm now testing against [vfmd-test](https://github.com/vfmd/vfmd-test) and ironing out some bugs. (SWIG bindings are not there yet.)

**Comment by jonschlinkert** [comment]
:+1: that's great! I know @chjj [has expressed](https://github.com/chjj/marked/blob/master/doc/broken.md) a similar opinion to mine that markdown needs an official spec. I'm looking forward to seeing where this goes!

**Comment by roop** [comment]
The parser is complete now. There's no other actionable item from this issue. Closing.
